# Generated by Django 2.2.1 on 2019-05-30 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('municipality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ethnicity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHERS', 'Others')],
                                            default='MALE', max_length=25)),
                ('family_members_count', models.PositiveIntegerField(default=None)),
                ('family_workers_count', models.PositiveIntegerField(default=None)),
                ('ethnicity',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_ethnicity',
                                   to='farmer.Ethnicity')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_group',
                                            to='municipality.Group')),
                ('municipality',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_municipality',
                                   to='municipality.Municipality')),
            ],
        ),
    ]
