# Generated by Django 2.2.1 on 2019-05-30 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CropMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CropName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('growing_period_from', models.DateField()),
                ('growing_period_to', models.DateField()),
                ('variety', models.CharField(max_length=50)),
                ('area', models.IntegerField(default=None)),
                ('production_in_kg', models.FloatField(default=None)),
                ('sales_in_kg', models.FloatField(default=None)),
                ('cost', models.FloatField(default=None)),
                ('general_cost', models.FloatField(default=None)),
                ('labor_cost', models.FloatField(default=None)),
                ('other_cost', models.FloatField(default=None)),
                ('area_type',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_crop_area',
                                   to='crop.CropArea')),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                             related_name='crop_farmer', to='farmer.Farmer')),
                ('method',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_crop_method',
                                   to='crop.CropMethod')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_crop_name',
                                           to='crop.CropName')),
            ],
        ),
    ]
