# Generated by Django 2.2.1 on 2019-05-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('crop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='growing_period_from',
            field=models.CharField(
                choices=[('JANUARY', 'January'), ('FEBRUARY', 'February'), ('MARCH', 'March'), ('APRIL', 'April'),
                         ('MAY', 'May'), ('JUNE', 'June'), ('JULY', 'July'), ('AUGUST', 'August'),
                         ('SEPTEMBER', 'September'), ('OCTOBER', 'October'), ('NOVEMBER', 'November'),
                         ('DECEMBER', 'December')], max_length=25),
        ),
        migrations.AlterField(
            model_name='crop',
            name='growing_period_to',
            field=models.CharField(
                choices=[('JANUARY', 'January'), ('FEBRUARY', 'February'), ('MARCH', 'March'), ('APRIL', 'April'),
                         ('MAY', 'May'), ('JUNE', 'June'), ('JULY', 'July'), ('AUGUST', 'August'),
                         ('SEPTEMBER', 'September'), ('OCTOBER', 'October'), ('NOVEMBER', 'November'),
                         ('DECEMBER', 'December')], max_length=25),
        ),
    ]
