# Generated by Django 2.2.1 on 2019-05-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0002_auto_20190530_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='growing_period_from',
            field=models.CharField(choices=[('BAISHAKH', 'Baishakh'), ('JETH', 'Jeth'), ('ASAR', 'Asar'), ('SAWAN', 'Sawan'), ('BHADAU', 'Bhadau'), ('ASOJ', 'Asoj'), ('KARTIK', 'Kartik'), ('MANGSIR', 'Mangsir'), ('POUSH', 'Poush'), ('MAGH', 'Magh'), ('FALGUN', 'Falgun'), ('CHAITRA', 'Chaitra')], max_length=25),
        ),
        migrations.AlterField(
            model_name='crop',
            name='growing_period_to',
            field=models.CharField(choices=[('BAISHAKH', 'Baishakh'), ('JETH', 'Jeth'), ('ASAR', 'Asar'), ('SAWAN', 'Sawan'), ('BHADAU', 'Bhadau'), ('ASOJ', 'Asoj'), ('KARTIK', 'Kartik'), ('MANGSIR', 'Mangsir'), ('POUSH', 'Poush'), ('MAGH', 'Magh'), ('FALGUN', 'Falgun'), ('CHAITRA', 'Chaitra')], max_length=25),
        ),
    ]
