# Generated by Django 2.2.1 on 2019-05-30 05:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('municipality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectorGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_collectors',
                 models.ManyToManyField(related_name='collector_group_data_collector', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(related_name='collector_group_group', to='municipality.Group')),
            ],
        ),
    ]
